name: Autobaseline Test Workflow

on:
  pull_request:
    branches: [ autobaseline ]
    
jobs:

  pipeline_scan:
      name: Pipeline Scan
      runs-on: ubuntu-latest

      steps:
        - name: checkout repo
          uses: actions/checkout@v2

        - name: Print GitHub Environment Variables
          run: |
            echo "GITHUB_BASE_REF: ${{ github.event.pull_request.base.ref }}"
            echo "GITHUB_REF: ${{ github.ref }}"
            echo "GITHUB_REPOSITORY: ${{ github.repository }}"
            echo "GITHUB_SHA: ${{ github.sha }}"
            echo "GITHUB_RUN_ID: ${{ github.run_id }}"
            echo "GITHUB_REF_NAME: ${{ github.ref_name }}"
        
        # run the pipeline scan action
        - name: pipeline-scan action step
          id: pipeline-scan
          uses: wasptree/veracode-autobaseline-pipeline@master
          with:
            vid: ${{ secrets.VID }}
            vkey: ${{ secrets.VKEY }}
            file: "./target/verademo.war"
            baseline_file: ".veracode-autobaseline/baseline.json"
            baseline_token: ${{ secrets.TOKEN }}
