name: Development Branch Workflow

on:
  push:
    branches: [ variables ]
  pull_request:
    branches: [ variables ]

jobs:
  print-env-vars:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Print GitHub Environment Variables
      run: |
        echo "GITHUB_BASE_REF: ${{ github.event.pull_request.base.ref }}"
        echo "GITHUB_REF: ${{ github.ref }}"
        echo "GITHUB_REPOSITORY: ${{ github.repository }}"
        echo "GITHUB_SHA: ${{ github.sha }}"
        echo "GITHUB_RUN_ID: ${{ github.run_id }}"
        echo "GITHUB_REF_NAME: ${{ github.ref_name }}"
